/**
 * BizimHesap Raporlar menü yapısı — 4 hub + tile katalogu.
 * status: live = gerçek Baykuş API / sayfa; oos = modül yok, boş/coming stub.
 */

export type ReportStatus = "live" | "oos";

export type ReportTile = {
  key: string;
  title: string;
  description?: string;
  href: string;
  color: string;
  status: ReportStatus;
  icon?: string;
};

export type ReportHub = {
  key: string;
  title: string;
  href: string;
  color: string;
  description: string;
  icon: string;
  tiles: ReportTile[];
};

export const REPORT_HUBS: ReportHub[] = [
  {
    key: "sales-purchases",
    title: "Satışlar - Alışlar",
    href: "/reports/sales-purchases",
    color: "#1f6feb",
    description: "Satış, alış, teklif ve ürün bazlı raporlar",
    icon: "🛒",
    tiles: [
      {
        key: "basit-satis",
        title: "Basit Satış",
        description: "Sipariş ciro · tarih/durum · CSV",
        href: "/reports/sales",
        color: "#2563eb",
        status: "live",
        icon: "📊",
      },
      {
        key: "urun-alis-satis",
        title: "Ürün Alış-Satış",
        description: "Ürün bazlı alış ve satış özeti",
        href: "/reports/product-buy-sell",
        color: "#0ea5e9",
        status: "live",
        icon: "📦",
      },
      {
        key: "cari-satis",
        title: "Cari Satışlar",
        description: "Müşteri bakiyeleri / alacaklar",
        href: "/reports/receivables",
        color: "#0891b2",
        status: "live",
        icon: "👥",
      },
      {
        key: "satis-kaybi",
        title: "Satış Kaybı",
        description: "Modül henüz yok",
        href: "/reports/oos?key=satis-kaybi&title=Sat%C4%B1%C5%9F%20Kayb%C4%B1",
        color: "#64748b",
        status: "oos",
        icon: "📉",
      },
      {
        key: "alislar",
        title: "Alışlar",
        description: "Satın alma belgelerinin özeti",
        href: "/reports/purchases",
        color: "#198754",
        status: "live",
        icon: "🏭",
      },
      {
        key: "iadeler",
        title: "İadeler",
        description: "İade modülü henüz yok",
        href: "/reports/oos?key=iadeler&title=%C4%B0adeler",
        color: "#64748b",
        status: "oos",
        icon: "↩️",
      },
      {
        key: "teklifler",
        title: "Teklifler",
        description: "Teklif listesi ve tutarlar",
        href: "/reports/quotes",
        color: "#7c3aed",
        status: "live",
        icon: "📝",
      },
      {
        key: "alti-aylik",
        title: "6 Aylık Satışlar",
        description: "Son 6 ay aylık ciro",
        href: "/reports/sales-6m",
        color: "#c2410c",
        status: "live",
        icon: "📅",
      },
      {
        key: "stok-satis-karsilama",
        title: "Stok-Satış Karşılama",
        description: "Stok vs satış miktarı",
        href: "/reports/stock-sales-coverage",
        color: "#0369a1",
        status: "live",
        icon: "⚖️",
      },
      {
        key: "kategori-satis",
        title: "Kategori Bazlı Satış",
        description: "Kategoriye göre ciro",
        href: "/reports/sales-by-category",
        color: "#db2777",
        status: "live",
        icon: "🏷️",
      },
    ],
  },
  {
    key: "financial",
    title: "Finansal Raporlar",
    href: "/reports/financial",
    color: "#7c3aed",
    description: "Kasa, banka, masraf, kâr-zarar ve cari",
    icon: "💰",
    tiles: [
      {
        key: "kasa-banka",
        title: "Kasa-Banka Hareketleri",
        description: "Giriş / çıkış · tarih filtre · CSV",
        href: "/reports/finance",
        color: "#7c3aed",
        status: "live",
        icon: "🏦",
      },
      {
        key: "calisanlar",
        title: "Çalışanlar",
        description: "Personel modülü yok",
        href: "/reports/oos?key=calisanlar&title=%C3%87al%C4%B1%C5%9Fanlar",
        color: "#64748b",
        status: "oos",
        icon: "👔",
      },
      {
        key: "vadesi-gecen",
        title: "Vadesi Geçen Alacaklar",
        description: "Açık cari alacaklar",
        href: "/reports/receivables",
        color: "#b45309",
        status: "live",
        icon: "⏰",
      },
      {
        key: "kdv",
        title: "KDV",
        description: "KDV raporu henüz yok",
        href: "/reports/oos?key=kdv&title=KDV",
        color: "#64748b",
        status: "oos",
        icon: "🧾",
      },
      {
        key: "masraflar",
        title: "Masraflar",
        description: "Gider dökümü · filtre + CSV",
        href: "/reports/expenses",
        color: "#be123c",
        status: "live",
        icon: "💸",
      },
      {
        key: "senetler",
        title: "Senetler",
        description: "Senet modülü yok",
        href: "/reports/oos?key=senetler&title=Senetler",
        color: "#64748b",
        status: "oos",
        icon: "📜",
      },
      {
        key: "ba-bs",
        title: "BA-BS",
        description: "BA/BS formu henüz yok",
        href: "/reports/oos?key=ba-bs&title=BA-BS",
        color: "#64748b",
        status: "oos",
        icon: "📋",
      },
      {
        key: "gelir-gider",
        title: "Gelir Gider",
        description: "Ciro vs alış maliyeti (kâr yaklaşımı)",
        href: "/reports/profit",
        color: "#ea580c",
        status: "live",
        icon: "📈",
      },
      {
        key: "hesap-bakiyeleri",
        title: "Hesap Bakiyeleri",
        description: "Kasa / banka / POS bakiyeleri",
        href: "/reports/account-balances",
        color: "#0f766e",
        status: "live",
        icon: "💳",
      },
      {
        key: "cekler",
        title: "Çekler",
        description: "Çek modülü yok",
        href: "/reports/oos?key=cekler&title=%C3%87ekler",
        color: "#64748b",
        status: "oos",
        icon: "✍️",
      },
      {
        key: "krediler",
        title: "Krediler",
        description: "Kredi / taksit listesi",
        href: "/finance/loans",
        color: "#6d28d9",
        status: "live",
        icon: "🏛️",
      },
      {
        key: "gunluk-giris-cikis",
        title: "Günlük Hesap Giriş Çıkış",
        description: "Günlük kasa paneli",
        href: "/finance/cash",
        color: "#198754",
        status: "live",
        icon: "🗓️",
      },
      {
        key: "borc-alacak-fis",
        title: "Borç Alacak Fişleri",
        description: "Tedarikçi borç-alacak fişi",
        href: "/suppliers/payables?fis=1",
        color: "#0d9488",
        status: "live",
        icon: "📄",
      },
      {
        key: "kullanici-satis",
        title: "Kullanıcı Satış-Tahsilat",
        description: "Kullanıcı bazlı satış henüz yok",
        href: "/reports/oos?key=kullanici-satis&title=Kullan%C4%B1c%C4%B1%20Sat%C4%B1%C5%9F-Tahsilat",
        color: "#64748b",
        status: "oos",
        icon: "👤",
      },
      {
        key: "cari-mizan",
        title: "Cari Mizan",
        description: "Cari döküm / ekstre",
        href: "/reports/cari-statements",
        color: "#115e59",
        status: "live",
        icon: "📑",
      },
      {
        key: "kar-zarar",
        title: "Kâr-Zarar",
        description: "Aylık kâr analizi",
        href: "/reports/profit",
        color: "#c2410c",
        status: "live",
        icon: "💹",
      },
      {
        key: "banka-durum",
        title: "Banka Durum",
        description: "Hesaplarım / banka listesi",
        href: "/finance/banks",
        color: "#1e40af",
        status: "live",
        icon: "🏛️",
      },
      {
        key: "tahsilat-odeme",
        title: "Tahsilat-Ödeme",
        description: "Açık bakiyeler",
        href: "/finance/open-balances",
        color: "#9f1239",
        status: "live",
        icon: "💵",
      },
      {
        key: "personel-maas",
        title: "Personel Maaş",
        description: "Personel / maaş modülü yok",
        href: "/reports/oos?key=personel-maas&title=Personel%20Maa%C5%9F",
        color: "#64748b",
        status: "oos",
        icon: "💼",
      },
      {
        key: "masraf-merkezi",
        title: "Masraf Merkezi",
        description: "Masraf kayıtları",
        href: "/finance/expenses",
        color: "#e11d48",
        status: "live",
        icon: "🗂️",
      },
      {
        key: "arsiv",
        title: "Belge Arşiv Merkezi",
        description: "PDF / evrak arşivi",
        href: "/reports/archive",
        color: "#111827",
        status: "live",
        icon: "🗄️",
      },
    ],
  },
  {
    key: "stock-reports",
    title: "Stok Raporları",
    href: "/reports/stock-reports",
    color: "#0369a1",
    description: "Ürün, hareket, depo ve kritik stok",
    icon: "📦",
    tiles: [
      {
        key: "urunler",
        title: "Ürünler",
        description: "Stok miktar / değer",
        href: "/reports/stock",
        color: "#0369a1",
        status: "live",
        icon: "📦",
      },
      {
        key: "stok-hareket",
        title: "Stok Hareketleri",
        description: "Giriş / çıkış hareketleri",
        href: "/reports/stock-movements",
        color: "#0284c7",
        status: "live",
        icon: "🔄",
      },
      {
        key: "depo-durumu",
        title: "Depo Durumu",
        description: "Depolar ve transfer",
        href: "/stock/warehouses",
        color: "#0e7490",
        status: "live",
        icon: "🏪",
      },
      {
        key: "stok-satis-karsilama-2",
        title: "Stok-Satış Karşılama",
        description: "Stok vs satış miktarı",
        href: "/reports/stock-sales-coverage",
        color: "#1d4ed8",
        status: "live",
        icon: "⚖️",
      },
      {
        key: "hareket-gormeyen",
        title: "Hareket Görmeyen Ürünler",
        description: "Son X günde hareket yok",
        href: "/reports/stock-idle",
        color: "#475569",
        status: "live",
        icon: "💤",
      },
      {
        key: "stok-durum",
        title: "Stok Durum",
        description: "Stok yönetimi",
        href: "/stock",
        color: "#0f766e",
        status: "live",
        icon: "📋",
      },
      {
        key: "envanter",
        title: "Envanter",
        description: "Stok değeri (maliyet/satış)",
        href: "/reports/stock",
        color: "#15803d",
        status: "live",
        icon: "🧮",
      },
      {
        key: "kritik",
        title: "Kritik",
        description: "Kritik stok altı ürünler",
        href: "/stock/critical",
        color: "#be123c",
        status: "live",
        icon: "⚠️",
      },
      {
        key: "depo-bazli",
        title: "Depo Bazlı",
        description: "Depo stokları",
        href: "/stock/warehouses",
        color: "#1e40af",
        status: "live",
        icon: "🏬",
      },
      {
        key: "sayim-farki",
        title: "Sayım Farkı",
        description: "Stok sayımı",
        href: "/stock/count",
        color: "#a16207",
        status: "live",
        icon: "🔢",
      },
      {
        key: "birlesik",
        title: "Birleşik Stok",
        description: "Ürün & stok merkezi",
        href: "/products",
        color: "#334155",
        status: "live",
        icon: "🔗",
      },
    ],
  },
  {
    key: "customer-list",
    title: "Müşteri Listesi",
    href: "/reports/customer-list",
    color: "#0f766e",
    description: "Kriterli müşteri / tedarikçi listesi",
    icon: "👥",
    tiles: [
      {
        key: "musteri-raporu",
        title: "Müşteri Listesi",
        description: "Filtre + Raporu Hazırla",
        href: "/reports/customer-list",
        color: "#0f766e",
        status: "live",
        icon: "👥",
      },
      {
        key: "tedarikci-listesi",
        title: "Tedarikçi Listesi",
        description: "Tedarikçiler + borç bakiyesi",
        href: "/reports/payables",
        color: "#198754",
        status: "live",
        icon: "🏭",
      },
      {
        key: "acik-alacaklar",
        title: "Açık Alacaklar",
        description: "Pozitif bakiyeli müşteriler",
        href: "/customers/receivables",
        color: "#be123c",
        status: "live",
        icon: "💰",
      },
    ],
  },
];

export function hubByKey(key: string): ReportHub | undefined {
  return REPORT_HUBS.find((h) => h.key === key);
}
